#ifndef QTASYNCSQLDATABASE_GLOBAL_H
#define QTASYNCSQLDATABASE_GLOBAL_H

#ifdef QTASYNCSQLDATABASE_LIBRARY
    #define QTASYNCSQLDATABASE_EXPORT Q_DECL_EXPORT
#else
    #define QTASYNCSQLDATABASE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTASYNCSQLDATABASE_GLOBAL_H
